repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.5.0
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.1
    hooks:
      - id: check-jsonschema
        name: "Match meta.ymls in one of the subdirectories of subworkflows/nf-core"
        files: ^subworkflows/nf-core/.*/meta\.yml$
        types: [yaml]
        args: ["--schemafile", "subworkflows/yaml-schema.json"]
      - id: check-github-workflows
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 37.408.2
    hooks:
      - id: renovate-config-validator
  # use ruff for python files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.1
    hooks:
      - id: ruff
        files: \.py$
        args: [--fix, --exit-non-zero-on-fix, "--select", "I,E1,E4,E7,E9,F,UP,N"] # sort imports and fix (rules taken from nf-core/tools)
      - id: ruff-format # formatter
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "3.2.1"
    hooks:
      - id: editorconfig-checker
        alias: ec
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
      - id: hadolint-docker
