name: "tcoffee_treealign"
description: Aligns sequences using T_COFFEE
keywords:
  - alignment
  - treealignment
  - MSA
  - genomics
  - msa
class: "msa_treealing"
tools:
  - "tcoffee":
      description: "A collection of tools for Computing, Evaluating and Manipulating
        Multiple Alignments of DNA, RNA, Protein Sequences and Structures."
      homepage: "http://www.tcoffee.org/Projects/tcoffee/"
      documentation: "https://tcoffee.readthedocs.io/en/latest/tcoffee_main_documentation.html"
      tool_dev_url: "https://github.com/cbcrg/tcoffee"
      doi: "10.1006/jmbi.2000.4042"
      licence: ["GPL v3"]
      identifier: "biotools:tcoffee"
  - "pigz":
      description: "Parallel implementation of the gzip algorithm."
      homepage: "https://zlib.net/pigz/"
      documentation: "https://zlib.net/pigz/pigz.pdf"
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test']`
    - fasta:
        type: file
        description: Input sequences in FASTA format
        pattern: "*.{fa,fasta}"
        ontologies:
          - edam: http://edamontology.org/format_1929
  - - meta2:
        type: map
        description: |
          Groovy Map containing tree information
          e.g. `[ id:'test_tree']`
    - tree:
        type: file
        description: Input guide tree in Newick format
        pattern: "*.{dnd}"
output:
  - alignment:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test']`
      - "*.aln.gz":
          type: file
          description: Alignment file in FASTA format. May be gzipped.
          pattern: "*.aln.gz"
          ontologies:
            - edam: http://edamontology.org/format_1984
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@luisas"
  - "@JoseEspinosa"
  - "@alessiovignoli"
maintainers:
  - "@luisas"
  - "@JoseEspinosa"
  - "@lrauschning"
  - "@alessiovignoli"
