# yaml-language-server: $schema=https://raw.githubusercontent.com/mirpedrol/class-modules/main/modules/yaml-schema.json
name: "{{ component_name_underscore }}"
description: Align sequences using {{ component }}
keywords:
  - alignment
  - msa
  - genomics
tools:
  - "{{ component }}":
      description: "{{ tool_description }}"
      homepage: "{{ tool_doc_url }}"
      documentation: "{{ tool_doc_url }}"
      tool_dev_url: "{{ tool_dev_url }}"
      doi: ""
      licence: { { tool_licence } }
      identifier: { { tool_identifier } }

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - fasta:
        type: file
        description: Input sequences in FASTA format
        pattern: "*.{fa,fasta}"
        ontologies:
          - edam: http://edamontology.org/format_1929

output:
  - alignment:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test']`
      - "*.aln.gz":
          type: file
          description: Alignment file, in FASTA format.
          pattern: "*.aln.gz"
          ontologies:
            - edam: http://edamontology.org/format_1984
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "{{ author }}"
maintainers:
  - "{{ author }}"
