name: "tcoffee_irmsd"
description: Computes the irmsd score for a given alignment and the structures.
keywords:
  - alignment
  - MSA
  - evaluation
tools:
  - "tcoffee":
      description: "A collection of tools for Multiple Alignments of DNA, RNA, Protein\
        \ Sequence"
      homepage: "http://www.tcoffee.org/Projects/tcoffee/"
      documentation: "https://tcoffee.readthedocs.io/en/latest/tcoffee_main_documentation.html"
      tool_dev_url: "https://github.com/cbcrg/tcoffee"
      doi: "10.1006/jmbi.2000.4042"
      licence: ["GPL v3"]
      identifier: "biotools:tcoffee"
  - "pigz":
      description: "Parallel implementation of the gzip algorithm."
      homepage: "https://zlib.net/pigz/"
      documentation: "https://zlib.net/pigz/pigz.pdf"

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', ... ]
    - msa:
        type: file
        description: fasta file containing the alignment to be evaluated. May be gzipped
          or uncompressed.
        pattern: "*.{aln,fa,fasta,fas}{.gz,}"
        ontologies:
          - edam: http://edamontology.org/format_1984
  - - meta2:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', ... ]
    - template:
        type: file
        description: T_coffee template file that maps sequences to the accessory information
          files to be used.
    - structure:
        type: file
        description: Structure file to be used in the alignment. For example, it could
          be protein structures or secondary structures.

output:
  - irmsd:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.irmsd:
          type: file
          description: File containing the irmsd of the alignment
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@luisas"
