# yaml-language-server: $schema=https://raw.githubusercontent.com/mirpedrol/class-modules/main/modules/meta-schema.json
name: "magus_align"
description: Multiple Sequence Alignment using Graph Clustering
keywords:
  - MSA
  - alignment
  - genomics
  - graph
  - msa
  - align
tools:
  - "magus":
      description: "Multiple Sequence Alignment using Graph Clustering"
      homepage: "https://github.com/vlasmirnov/MAGUS"
      documentation: "https://github.com/vlasmirnov/MAGUS"
      tool_dev_url: "https://github.com/vlasmirnov/MAGUS"
      doi: "10.1093/bioinformatics/btaa992"
      licence: ["MIT"]
      identifier: biotools:magus

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing the fasta meta information
          e.g. `[ id:'test', single_end:false ]`
    - fasta:
        type: file
        description: Input sequences in FASTA format.
        pattern: "*.{fa,fasta}"
        ontologies:
          - edam: http://edamontology.org/format_1929
output:
  - alignment:
      - meta:
          type: map
          description: |
            Groovy Map containing sample meta information.
            e.g. `[ id:'test', single_end:false ]`
      - "*.aln.gz":
          type: file
          description: File containing the output alignment, in FASTA format containing
            gaps. The sequences may be in a different order than in the input FASTA.
          pattern: "*.aln.gz"
          ontologies:
            - edam: http://edamontology.org/format_1984
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@lrauschning"
