name: "clustalo_align"
description: Align sequences using Clustal Omega
keywords:
  - alignment
  - MSA
  - genomics
tools:
  - "clustalo":
      description: "Latest version of Clustal: a multiple sequence alignment program
        for DNA or proteins"
      homepage: "http://www.clustal.org/omega/"
      documentation: "http://www.clustal.org/omega/"
      tool_dev_url: "http://www.clustal.org/omega/"
      doi: "10.1038/msb.2011.75"
      licence: ["GPL v2"]
      identifier: "biotools:clustalo"
  - "pigz":
      description: "Parallel implementation of the gzip algorithm."
      homepage: "https://zlib.net/pigz/"
      documentation: "https://zlib.net/pigz/pigz.pdf"
input:
  - - meta:
        qualifier: val
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test']`
    - fasta:
        qualifier: path
        type: file
        description: Input sequences in FASTA format
        pattern: "*.{fa,fasta}"
        ontologies:
          - edam: http://edamontology.org/format_1929
  - - meta2:
        qualifier: val
        type: map
        description: |
          Groovy Map containing tree information
          e.g. `[ id:'test_tree']`
    - tree:
        qualifier: path
        type: file
        description: Input guide tree in Newick format
        pattern: "*.{dnd}"
  - - compress:
        qualifier: val
        type: boolean
        description: Flag representing whether the output MSA should be compressed.
          Set to true to enable/false to disable compression. Compression is done using
          pigz, and is multithreaded.
output:
  - alignment:
      - meta:
          qualifier: val
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test']`
      - "*.aln{.gz,}":
          qualifier: path
          type: file
          description: Alignment file, in gzipped fasta format
          pattern: "*.aln{.gz,}"
          ontologies:
            - edam: http://edamontology.org/format_1984
  - versions:
      - versions.yml:
          qualifier: path
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@luisas"
  - "@joseespinosa"
maintainers:
  - "@luisas"
  - "@joseespinosa"
  - "@lrauschning"
