# yaml-language-server: $schema=https://raw.githubusercontent.com/mirpedrol/class-modules/main/modules/yaml-schema.json
name: "clustalo_guidetree"
description: Renders a guidetree in clustalo
keywords:
  - guide tree
  - msa
  - newick
tools:
  - "clustalo":
      description: "Latest version of Clustal: a multiple sequence alignment program
        for DNA or proteins"
      homepage: "http://www.clustal.org/omega/"
      documentation: "http://www.clustal.org/omega/"
      tool_dev_url: "http://www.clustal.org/omega/"
      doi: "10.1038/msb.2011.75"
      licence: ["GPL v2"]
      identifier: "biotools:clustalo"
input:
  - - meta:
        qualifier: val
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test']`
    - fasta:
        qualifier: path
        type: file
        description: Input sequences in FASTA format
        pattern: "*.{fa,fasta}"
output:
  - tree:
      - meta:
          qualifier: val
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test']`
      - "*.dnd":
          qualifier: path
          type: file
          description: Guide tree file in Newick format
          pattern: "*.{dnd}"
  - versions:
      - versions.yml:
          qualifier: path
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@luisas"
  - "@JoseEspinosa"
maintainers:
  - "@luisas"
  - "@JoseEspinosa"
