# yaml-language-server: $schema=https://raw.githubusercontent.com/mirpedrol/class-modules/main/subworkflows/yaml-schema.json
name: "msa_treealign"
description: Perform multiple sequence alignment from a provided guide tree
keywords: ["alignment", "treealignment", "msa"]
components:
  - clustalo/align:
      git_remote: "https://github.com/nf-core/modules.git"
  - famsa/align:
      git_remote: "https://github.com/nf-core/modules.git"
  - magus/align:
      git_remote: "https://github.com/nf-core/modules.git"
  - tcoffee/align:
      git_remote: "https://github.com/nf-core/modules.git"

input:
  - ch_fasta:
      description: "Channel containing: meta, fasta"
      structure:
        - meta:
            description: "Groovy Map containing sample information

              e.g. `[ id:'test']`

              "
            type: map
        - fasta:
            description: Input sequences in FASTA format
            ontologies:
              - edam: http://edamontology.org/format_1929
            pattern: "*.{fa,fasta}"
            type: file
        - tool:
            description: The name of the tool to run
            type: string
  - ch_tree:
      description: "Channel containing: meta, fasta"
      structure:
        - meta2:
            description: "Groovy Map containing tree information

              e.g. `[ id:'test_tree']`

              "
            type: map
        - tree:
            description: Input guide tree in Newick format
            pattern: "*.{dnd}"
            type: file
        - tool:
            description: The name of the tool to run
            type: string

output:
  - alignment:
      description: Output channel alignment
      structure:
        - - meta:
              description: "Groovy Map containing sample information

                e.g. `[ id:'test']`

                "
              type: map
          - "*.aln.gz":
              description: Alignment file, in gzipped fasta format
              ontologies:
                - edam: http://edamontology.org/format_1984
              pattern: "*.aln.gz"
              type: file
  - versions:
      description: Output channel versions
      structure:
        - versions.yml:
            description: File containing software versions
            ontologies:
              - edam: http://edamontology.org/format_3750
            pattern: versions.yml
            type: file

authors:
  - "@mirpedrol"
maintainers:
  - "@mirpedrol"
