---
# yaml-language-server: $schema=https://raw.githubusercontent.com/mirpedrol/class-modules/master/modules/environment-schema.json
name: "tcoffee_tcs"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::t-coffee=13.46.0.919e8c6b"
  - conda-forge::pigz=2.8
