# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "clustalo_alignment"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::clustalo=1.2.4"
