# yaml-language-server: $schema=https://raw.githubusercontent.com/mirpedrol/class-modules/main/modules/yaml-schema.json
name: "famsa_treealign"
description: Aligns sequences using FAMSA
keywords:
  - alignment
  - treealignment
  - MSA
  - msa
  - genomics
tools:
  - "famsa":
      description: "Algorithm for large-scale multiple sequence alignments"
      homepage: "https://github.com/refresh-bio/FAMSA"
      documentation: "https://github.com/refresh-bio/FAMSA"
      tool_dev_url: "https://github.com/refresh-bio/FAMSA"
      doi: "10.1038/srep33964"
      licence: ["GPL v3"]
      identifier: biotools:famsa
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test']`
    - fasta:
        type: file
        description: Input sequences in FASTA format
        pattern: "*.{fa,fasta}"
        ontologies:
          - edam: http://edamontology.org/format_1929
  - - meta2:
        type: map
        description: |
          Groovy Map containing tree information
          e.g. `[ id:'test_tree']`
    - tree:
        type: file
        description: Input guide tree in Newick format
        pattern: "*.{dnd}"
output:
  - alignment:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test']`
      - "*.aln.gz":
          type: file
          description: Alignment file, in FASTA format.
          pattern: "*.aln.gz"
          ontologies:
            - edam: http://edamontology.org/format_1984
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@luisas"
  - "@JoseEspinosa"
maintainers:
  - "@luisas"
  - "@JoseEspinosa"
