# yaml-language-server: $schema=https://raw.githubusercontent.com/mirpedrol/class-modules/main/subworkflows/meta-schema.json
name: "msa_guidetree"
description: Compute a guide tree for multiple sequence alignment
keywords: ["align", "guide tree", "guidetree", "msa"]
components: ["famsa/guidetree", "magus/guidetree", "clustalo/guidetree"]

input:
  - ch_fasta:
      description: "Channel containing: meta, fasta"
      structure:
        - meta:
            description: "Groovy Map containing sample information

              e.g. `[ id:'test']`

              "
            type: map
        - fasta:
            description: Input sequences in FASTA format
            ontologies:
              - edam: http://edamontology.org/format_1929
            pattern: "*.{fa,fasta}"
            type: file

output:
  - tree:
      description: Output channel tree
      structure:
        - meta:
            description: "Groovy Map containing sample information

              e.g. `[ id:'test']`

              "
            type: map
        - "*.dnd":
            description: Guide tree file in Newick format
            pattern: "*.{dnd}"
            type: file
  - versions:
      description: Output channel versions
      structure:
        - versions.yml:
            description: File containing software versions
            pattern: versions.yml
            type: file

authors:
  - "@mirpedrol"
maintainers:
  - "@mirpedrol"
