# yaml-language-server: $schema=https://raw.githubusercontent.com/mirpedrol/class-modules/main/subworkflows/yaml-schema.json
name: "msa_alignment"
description: Perform multiple sequence alignment
keywords: ["alignment", "msa", "align"]
components:
  [
    "mafft",
    "kalign/align",
    "famsa/align",
    "muscle5/super5",
    "magus/align",
    "clustalo/align",
    "tcoffee/align",
    "learnmsa/align",
  ]

input:
  - ch_fasta:
      description: "Channel containing: meta, fasta"
      structure:
        - meta:
            description: "Groovy Map containing sample information

              e.g. `[ id:'sample1', single_end:false ]`

              "
            type: map
        - fasta:
            description: Input sequences in FASTA format
            ontologies:
              - edam: http://edamontology.org/format_1929
            pattern: "*.{fa,fasta}"
            type: file

output:
  - alignment:
      description: Output channel alignment
      structure:
        - meta:
            description: "Groovy Map containing sample information

              e.g. `[ id:'test']`

              "
            type: map
        - "*.aln.gz":
            description: Alignment file, in FASTA format.
            ontologies:
              - edam: http://edamontology.org/format_1984
            pattern: "*.aln.gz"
            type: file
  - versions:
      description: Output channel versions
      structure:
        - versions.yml:
            description: File containing software versions
            pattern: versions.yml
            type: file

authors:
  - "@mirpedrol"
maintainers:
  - "@mirpedrol"
