# yaml-language-server: $schema=https://raw.githubusercontent.com/mirpedrol/class-modules/main/subworkflows/yaml-schema.json
name: "msa_alignment"
description: Perform multiple sequence alignment
keywords: ["alignment", "msa", "align"]
components:
  - clustalo/align:
      git_remote: "https://github.com/nf-core/modules.git"
  - famsa/align:
      git_remote: "https://github.com/nf-core/modules.git"
  - kalign/align:
      git_remote: "https://github.com/nf-core/modules.git"
  - learnmsa/align:
      git_remote: "https://github.com/nf-core/modules.git"
  - mafft/align:
      git_remote: "https://github.com/nf-core/modules.git"
  - magus/align:
      git_remote: "https://github.com/nf-core/modules.git"
  - muscle5/super5:
      git_remote: "https://github.com/nf-core/modules.git"
  - tcoffee/align:
      git_remote: "https://github.com/nf-core/modules.git"
  - tcoffee/regressive:
      git_remote: "https://github.com/nf-core/modules.git"
  - upp/align:
      git_remote: "https://github.com/nf-core/modules.git"

input:
  - ch_fasta:
      description: "Channel containing: meta, fasta"
      structure:
        - meta:
            description: "Groovy Map containing sample information

              e.g. `[ id:'sample1', single_end:false ]`

              "
            type: map
        - fasta:
            description: Input sequences in FASTA format
            ontologies:
              - edam: http://edamontology.org/format_1929
            pattern: "*.{fa,fasta}"
            type: file
        - tool:
            description: The name of the tool to run
            type: string

output:
  - alignment:
      description: Output channel alignment
      structure:
        - - meta:
              description: "Groovy Map containing sample information

                e.g. `[ id:'test']`

                "
              type: map
          - "*.aln.gz":
              description: Alignment file, in FASTA format.
              ontologies:
                - edam: http://edamontology.org/format_1984
              pattern: "*.aln.gz"
              type: file
  - versions:
      description: Output channel versions
      structure:
        - versions.yml:
            description: File containing software versions
            ontologies:
              - edam: http://edamontology.org/format_3750
            pattern: versions.yml
            type: file

authors:
  - "@mirpedrol"
maintainers:
  - "@mirpedrol"
