# yaml-language-server: $schema=https://raw.githubusercontent.com/mirpedrol/class-modules/main/modules/meta-schema.json
name: "mtmalign_align"
description: Aligns protein structures using mTM-align
keywords:
  - alignment
  - MSA
  - genomics
  - structure
tools:
  - "mTM-align":
      description: "Algorithm for structural multiple sequence alignments"
      homepage: "http://yanglab.nankai.edu.cn/mTM-align/"
      documentation: "http://yanglab.nankai.edu.cn/mTM-align/help/"
      tool_dev_url: "http://yanglab.nankai.edu.cn/mTM-align/"
      doi: "10.1093/bioinformatics/btx828"
      licence: ["None"]
      identifier: "biotools:mtm-align"
  - "pigz":
      description: "Parallel implementation of the gzip algorithm."
      homepage: "https://zlib.net/pigz/"
      documentation: "https://zlib.net/pigz/pigz.pdf"

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test']`
    - pdbs:
        type: file
        description: Input protein structures in PDB format. Files may be gzipped or
          uncompressed. They should contain exactly one chain!
        pattern: "*.pdb{.gz}"
output:
  - alignment:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test']`
      - "${prefix}.aln.gz":
          type: file
          description: Alignment in FASTA format.
          pattern: "*.aln.gz"
          ontologies:
            - edam: http://edamontology.org/format_1984
  - structure:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test']`
      - "${prefix}.pdb.gz":
          type: file
          description: Overlaid structures in PDB format.
          pattern: "${prefix}.pdb{.gz,}"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@lrauschning"
maintainers:
  - "@lrauschning"
