# yaml-language-server: $schema=https://raw.githubusercontent.com/mirpedrol/class-modules/main/modules/yaml-schema.json
name: "magus_guidetree"
description: Multiple Sequence Alignment using Graph Clustering
keywords:
  - MSA
  - guidetree
  - genomics
  - graph
tools:
  - "magus":
      description: "Multiple Sequence Alignment using Graph Clustering"
      homepage: "https://github.com/vlasmirnov/MAGUS"
      documentation: "https://github.com/vlasmirnov/MAGUS"
      tool_dev_url: "https://github.com/vlasmirnov/MAGUS"
      doi: "10.1093/bioinformatics/btaa992"
      licence: ["MIT"]
      identifier: biotools:magus

input:
  - - meta:
        qualifier: val
        type: map
        description: |
          Groovy Map containing fasta meta information
          e.g. `[ id:'test', single_end:false ]`
    - fasta:
        qualifier: path
        type: file
        description: Input sequences in FASTA format.
        pattern: "*.{fa,fna,fasta}"
        ontologies:
          - edam: http://edamontology.org/format_1929
output:
  - tree:
      - meta:
          qualifier: val
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*.tree":
          qualifier: path
          type: file
          description: File containing the output guidetree, in newick format.
          pattern: "*.tree"
  - versions:
      - versions.yml:
          qualifier: path
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@lrauschning"
