# yaml-language-server: $schema=https://raw.githubusercontent.com/mirpedrol/class-modules/main/modules/yaml-schema.json
name: "foldmason_easymsa"
description: Perform multiple sequence alignment of protein structures
keywords: ["alignment", "msa", "structure"]
class: "msa_structural_alignment"
tools:
  - "foldmason":
      description: "Multiple Protein Structure Alignment at Scale with FoldMason"
      homepage: "https://github.com/steineggerlab/foldmason"
      documentation: "https://github.com/steineggerlab/foldmason"
      tool_dev_url: "https://github.com/steineggerlab/foldmason"
      doi: "10.1101/2024.08.01.606130"
      licence: ["GPL v3"]
      identifier: biotools:foldmason

input:
  - - meta:
        description: "Groovy Map containing sample information

          e.g. `[ id:'sample1' ]`

          "
        type: map
    - pdbs:
        description: Input protein structures in PDB format.
        ontologies:
          - edam: http://edamontology.org/format_1476
          - edam: http://edamontology.org/format_1477
        pattern: "*.{pdb,mmcif}"
        type: file

output:
  - alignment:
      - meta:
          description: "Groovy Map containing sample information

            e.g. `[ id:'test']`

            "
          type: map
      - ${prefix}.aln.gz:
          description: Alignment in FASTA format. May be gzipped or uncompressed.
          ontologies:
            - edam: http://edamontology.org/format_1984
          pattern: "*.{aln.gz,aln,fa,fa.gz,fasta,fasta.gz}"
          type: file
  - versions:
      - versions.yml:
          description: File containing software versions
          pattern: versions.yml
          type: file

authors:
  - "@mirpedrol"
maintainers:
  - "@mirpedrol"
