name: "kalign_align"
description: "Aligns sequences using kalign"
keywords:
  - alignment
  - MSA
  - genomics
  - msa
  - align
tools:
  - "kalign":
      description: "Kalign is a fast and accurate multiple sequence alignment algorithm."
      homepage: "https://msa.sbc.su.se/cgi-bin/msa.cgi"
      documentation: "https://github.com/TimoLassmann/kalign"
      tool_dev_url: "https://github.com/TimoLassmann/kalign"
      doi: "10.1093/bioinformatics/btz795"
      licence: ["GPL v3"]
      identifier: "biotools:kalign"
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test']`
    - fasta:
        type: file
        description: Input sequences in FASTA format. May be gzipped or uncompressed.
        pattern: "*.{fa,fasta}{.gz,}"
        ontologies:
          - edam: http://edamontology.org/format_1929
output:
  - alignment:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test']`
      - "*.aln.gz":
          type: file
          description: Alignment file.
          pattern: "*.aln.gz"
          ontologies:
            - edam: http://edamontology.org/format_1984
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@luisas"
  - "@JoseEspinosa"
maintainers:
  - "@luisas"
  - "@JoseEspinosa"
