# yaml-language-server: $schema=https://raw.githubusercontent.com/mirpedrol/class-modules/main/modules/yaml-schema.json
name: "famsa_guidetree"
description: Renders a guidetree in famsa
keywords:
  - guide tree
  - msa
  - newick
tools:
  - "famsa":
      description: "Algorithm for large-scale multiple sequence alignments"
      homepage: "https://github.com/refresh-bio/FAMSA"
      documentation: "https://github.com/refresh-bio/FAMSA"
      tool_dev_url: "https://github.com/refresh-bio/FAMSA"
      doi: "10.1038/srep33964"
      licence: ["GPL v3"]
      identifier: biotools:famsa
input:
  - - meta:
        qualifier: val
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test']`
    - fasta:
        qualifier: path
        type: file
        description: Input sequences in FASTA format
        pattern: "*.{fa,fasta}"
        ontologies:
          - edam: http://edamontology.org/format_1929
output:
  - tree:
      - meta:
          qualifier: val
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test']`
      - "*.dnd":
          qualifier: path
          type: file
          description: Guide tree file in Newick format
          pattern: "*.{dnd}"
  - versions:
      - versions.yml:
          qualifier: path
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@luisas"
  - "@JoseEspinosa"
maintainers:
  - "@luisas"
  - "@JoseEspinosa"
