name: "learnmsa_align"
description: Align sequences using learnMSA
keywords:
  - alignment
  - MSA
  - genomics
  - msa
  - align
class: "msa_alignment"
tools:
  - "learnmsa":
      description: "learnMSA: Learning and Aligning large Protein Families"
      homepage: "https://github.com/Gaius-Augustus/learnMSA"
      documentation: "https://github.com/Gaius-Augustus/learnMSA"
      tool_dev_url: "https://github.com/Gaius-Augustus/learnMSA"
      doi: "10.1093/gigascience/giac104"
      licence: ["MIT"]
      identifier: biotools:learnMSA
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test']`
    - fasta:
        type: file
        description: Input sequences in FASTA format. May be gz-compressed or uncompressed.
        pattern: "*.{fa,fasta}"
        ontologies:
          - edam: http://edamontology.org/format_1929
output:
  - alignment:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test']`
      - "*.aln.gz":
          type: file
          description: Alignment file, in FASTA format.
          pattern: "*.aln.gz"
          ontologies:
            - edam: http://edamontology.org/format_1984
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@luisas"
  - "@JoseEspinosa"
maintainers:
  - "@luisas"
  - "@JoseEspinosa"
