name: mafft
description: Multiple sequence alignment using MAFFT
keywords:
  - fasta
  - msa
  - multiple sequence alignment
  - alignment
  - align
class: "msa_alignment"
tools:
  - "mafft":
      description: Multiple alignment program for amino acid or nucleotide sequences
        based on fast Fourier transform
      homepage: https://mafft.cbrc.jp/alignment/software/
      documentation: https://mafft.cbrc.jp/alignment/software/manual/manual.html
      tool_dev_url: https://mafft.cbrc.jp/alignment/software/source.html
      doi: "10.1093/nar/gkf436"
      licence: ["BSD"]
      identifier: biotools:MAFFT
  - "pigz":
      description: "Parallel implementation of the gzip algorithm."
      homepage: "https://zlib.net/pigz/"
      documentation: "https://zlib.net/pigz/pigz.pdf"

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fasta:
        type: file
        description: FASTA file containing the sequences to align. May be gzipped or
          uncompressed.
        pattern: "*.{fa,fasta}"
        ontologies:
          - edam: http://edamontology.org/format_1929
output:
  - alignment:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.aln.gz":
          type: file
          description: Aligned sequences in FASTA format.
          pattern: "*.aln.gz"
          ontologies:
            - edam: http://edamontology.org/format_1984
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@MillironX"
maintainers:
  - "@MillironX"
  - "@Joon-Klaps"
